repos:
  - repo: local
    hooks:
      - id: check-yaml
        name: check-yaml
        entry: check-yaml
        language: system
        types: [ yaml ]
      - id: check-toml
        name: check-toml
        entry: check-toml
        language: system
        types: [ toml ]
      - id: check-case-conflict
        name: check-case-conflict
        entry: check-case-conflict
        language: system
