baseURL = "https://viseshprasad.com/"
languageCode = "en-us"
title = "viseshprasad.com"
theme = "ink"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

pygmentsstyle = "trac"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

summaryLength = 20
enableEmoji = true

[params]
subtitle = "Thoughts and brain dumps of a 1x engineer"
# Optional 64x64 avatar image.
avatar = "https://raw.githubusercontent.com/viseshrp/website/main/prof.jpeg"
featherIconsCDN = true
mode = "auto" # "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/viseshrp"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/viseshprasad/"

[[params.social]]
name = "Resume"
icon = "file"
url = "https://drive.google.com/file/d/0B6KvjIoOCo4denFodnh2akItZFU/view?usp=sharing"

[taxonomies]
tag = "tags"
