name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install linter requirements
        run: pip install -r requirements-lint.txt

      - name: Run all pre-commit checks
        run: |
          pre-commit run --all-files --verbose --show-diff-on-failure

  md-lint:
    name: "Markdown linting"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - name: Lint Code Base
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "README.md,content/**/*.md"
          separator: ','
          command: fix

  cspell:
    name: "cspell"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "12"
      - run: npm install -g cspell
      - run: cspell --config ./cspell.json --no-progress "content/**/*.md"

  deploy:
    runs-on: self-hosted
    needs: [ lint, md-lint, cspell ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --enableGitInfo

      - name: List directory structure
        run: pwd && ls -ltR

      - name: Deploy
        run: rsync -rav ./public ./nginx/* /opt/blog
