name: GitHub Pages

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
            extended: true

      - name: Build
        run: hugo --minify

      - name: List directory structure
        run: pwd && ls -ltR

      - name: Deploy
        run: rsync -rav ./public /opt/blog

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public